version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    volumes:
      #- './sqlserver:/var/opt/mssql'
      - './database.sql:/scripts/database.sql'

    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: as12AS!@
    ports:
      - 1433:1433
